apiVersion: v1
kind: Service
metadata:
  name: mysql-headless 
  namespace: expense
spec:
  clusterIP: None # This makes it a headless service, which is required for StatefulSets to manage their own network identities
  selector:
    component: mysql
    project: expense
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql 
    project: expense
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      # has to match .spec.template.metadata.labels
      component: mysql 
      project: expense
      tier: database
  serviceName: "mysql-headless" # This is the name of the headless service that will manage the network identities of the pods
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: mysql 
        project: expense
        tier: database
    spec:
      containers:
      - name: mysql
        image: tgsmanimohan/mysql:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
# Pod template does not support volumeClaimTemplates, so we need to define the PVC separately and reference it here
volumeClaimTemplates:
- metadata:
    name: mysql
  spec:
    storageClassName: expense-ebs-sc # Reference the custom StorageClass
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
      storage: 1Gi
      # nodeSelector:
      #   topology.kubernetes.io/zone: us-east-1d
      # volumes:
      # - name: mysql
      #   persistentVolumeClaim:
      #     claimName: mysql
---


 